/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'background':                'var(--color-background)',
        'surface':                   'var(--color-surface)',
        'surface-dim':               '#151312',
        'surface-bright':            '#3b3937',
        'surface-container-lowest':  '#100e0d',
        'surface-container-low':     '#1d1b1a',
        'surface-container':         'var(--color-surface-container)',
        'surface-container-high':    'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'surface-variant':           '#373433',
        'surface-tint':              '#dac2af',
        'on-surface':                'var(--color-on-surface)',
        'on-surface-variant':        'var(--color-on-surface-variant)',
        'on-background':             'var(--color-on-surface)',
        'inverse-surface':           '#e7e1df',
        'inverse-on-surface':        '#32302e',
        'outline':                   '#9a8f86',
        'outline-variant':           'var(--color-outline-variant)',
        'primary':                   'var(--color-primary)',
        'primary-fixed':             '#f8deca',
        'primary-fixed-dim':         '#dac2af',
        'primary-container':         '#26190d',
        'on-primary':                '#3c2d20',
        'on-primary-container':      '#95806f',
        'on-primary-fixed':          '#26190d',
        'on-primary-fixed-variant':  '#544435',
        'inverse-primary':           '#6d5b4b',
        'secondary':                 '#cfc5ba',
        'secondary-fixed':           '#ece1d6',
        'secondary-fixed-dim':       '#cfc5ba',
        'secondary-container':       '#4f4840',
        'on-secondary':              '#352f28',
        'on-secondary-container':    '#c1b7ad',
        'on-secondary-fixed':        '#201b14',
        'on-secondary-fixed-variant':'#4c463e',
        'tertiary':                  'var(--color-tertiary)',
        'tertiary-fixed':            '#d3eca0',
        'tertiary-fixed-dim':        '#b7cf87',
        'tertiary-container':        '#141f00',
        'on-tertiary':               '#243600',
        'on-tertiary-container':     '#768c4b',
        'on-tertiary-fixed':         '#141f00',
        'on-tertiary-fixed-variant': '#3a4d13',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
        'on-error-container':        '#ffdad6',
      },
      fontFamily: {
        sora:              ['Sora', 'sans-serif'],
        'hanken-grotesk':  ['Hanken Grotesk', 'sans-serif'],
        'jetbrains-mono':  ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        sm:      '0.25rem',
        DEFAULT: '0.5rem',
        md:      '0.75rem',
        lg:      '1rem',
        xl:      '1.5rem',
        full:    '9999px',
      },
    },
  },
  plugins: [],
}
